In [1]:
import numpy as np

In [2]:
result = []
linedict = {}

In [3]:
board = [[0,0,0,0,0],[0,0,1,0,3],[0,2,5,0,1],[4,2,4,4,2],[3,5,1,3,1]]
for b in board:
    print(np.array(b))

[0 0 0 0 0]
[0 0 1 0 3]
[0 2 5 0 1]
[4 2 4 4 2]
[3 5 1 3 1]


In [72]:
# 딕셔너리의 키 생성
N = 5
linedict = linedict.fromkeys(range(1,N+1))
linedict

{1: None, 2: None, 3: None, 4: None, 5: None}

In [73]:
for i in range(N):
    for j in range(N):
        print(j,i)

0 0
1 0
2 0
3 0
4 0
0 1
1 1
2 1
3 1
4 1
0 2
1 2
2 2
3 2
4 2
0 3
1 3
2 3
3 3
4 3
0 4
1 4
2 4
3 4
4 4


In [74]:
# 딕셔너리 벨류 생성
N=5
board = [[0,0,0,0,0],[0,0,1,0,3],[0,2,5,0,1],[4,2,4,4,2],[3,5,1,3,1]]
for i in range(N):
    linedict[i+1]=[]
    for j in range(N):
        linedict[i+1].append(board[j][i])

In [75]:
# i=0
# [x[i] for x in board]

# for i in range(5):
#     linedict[i+1] = [x[i] for x in board] 

In [76]:
for l in linedict.values():
    for i in l[:]:
        if i == 0:
            l.remove(i)

In [77]:
linedict

{1: [4, 3], 2: [2, 2, 5], 3: [1, 5, 4, 1], 4: [4, 3], 5: [3, 1, 2, 1]}

In [78]:
moves = [1,5,3,5,1,2,1,4]
result = []
for m in moves:
    if not linedict[m]: #만약 값이 없으면
        result.append(" ") #빈칸으로 채우기
    else:
        result.append(linedict[m][0]) #값이 있으면 젤 위에 있는 값을 result에 넣기
        linedict[m].pop(0)  # dictionary value값 삭제 

# result = [4,3,1,1,3,2,"",4]

In [79]:
result

[4, 3, 1, 1, 3, 2, ' ', 4]

In [51]:
result[:][2]

1

In [66]:
cnt = 0
a = [1,2,3,4,4,5]
for x in a[:]:
    if x == 4:
        a.remove(x)
        cnt+=1

In [67]:
cnt

2

In [68]:
result2 = result.copy()
result2

[4, 3, 1, 1, 3, 2, ' ', 4]

In [57]:
# 중복되는 값은 지워보자.
cnt = 0
i = 0
while i < len(result):
    for i in range(len(result2)-1): # i=0~6
        if result2[i] == result2[i+1]:
            result.remove(result[i])
            result.remove(result[i+1])
            cnt+=2
            i+=1
        else:
            i+=1
            continue


ValueError: list.remove(x): x not in list

In [56]:
result

[4, 3, 1, 1, 3, 2, ' ', 4]

In [40]:
cnt

2

In [ ]:

]


In [ ]:
linedict = linedict.fromkeys(range(1,N+1)) #딕셔너리 key 생성
for i in range(N):
    linedict[i+1]=[]
    for j in range(N):
        linedict[i+1].append(board[j][i]) #딕셔너리 value 생성

for l in linedict.values():
    for i in l[:]: #딕셔너리의 value를 복사하는 이유 : remove를 하면서 인덱스 누락이 발생하기 때문(따라서 원본 복사본을 통해 제거)
        if i == 0:
            l.remove(i)

result = []
for m in moves:
    if not linedict[m]: #만약 값이 없으면
        result.append(" ") #빈칸으로 채우기
    else:
        result.append(linedict[m][0]) #값이 있으면 젤 위에 있는 값을 result에 넣기
        linedict[m].pop(0)  # dictionary value값 삭제 

